name: Generate Snake Animation
# 触发规则：每天自动运行 + 手动可运行
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 生成贪吃蛇贡献图
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          # github 用户名（**改成你自己的！**）
          github_user_name: Mrkuzumi
          # 生成的动画保存路径
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 推送到仓库
      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
